theme: jekyll-theme-slate
title: Welcome
description: These are courses from some of the best schools in the country taken via the edX and Coursera platforms. They led me to put together several interesting projects.
